import "./globals.css";
import Navigation from "../components/Navigation";
import Footer from "../components/Footer";
import { MantineProvider } from '@mantine/core';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ backgroundColor: '#efe8e3' }}>
        <Navigation/>
          <main>
            <MantineProvider
              withGlobalStyles
              withNormalizeCSS
              theme={{
                colorScheme: 'light', // or 'dark'
              }}
            >
              {children}
            </MantineProvider>
          </main>
        <Footer/>
      </body>
    </html>
  );
}